version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: feedpulse-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: feedpulse-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/feedpulse
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:4000
    container_name: feedpulse-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  mongo_data: